### ISSUE TITLE
add ibis to depdency graph

### ISSUE THREAD

**Issue by hunterowens** [CityOfLosAngeles/intake-civis#3]
I'm open to hearing why not to do so, but think it would make sense to add it to the package specs?

**Comment by ian-r-rose** [comment]
It's in there, but as an optional dependency: https://github.com/CityOfLosAngeles/intake-civis/blob/5fa106e264c63aae2fd41b0f1a869a74e8906673/setup.py#L23-L25

I wanted to make a minimal install that didn't have any difficult dependencies (ibis isn't too tricky, but geopandas is).

To get the full install, you have to enter `pip install intake-civis[ibis, geospatial]` , e.g. [this](https://github.com/CityOfLosAngeles/aqueduct/blob/b61830afed601506537e0bfa05277b0565c64d75/civis/Dockerfile#L81)
